### ISSUE TITLE
Failing to retrieve sequences

### ISSUE THREAD

**Issue by Joana-V** [RaphaelHebert/nsdpy#42] opened 2024-01-22 16:23 UTC
Hi, 

I've been using NSDPY to retrieve mitochondrial sequences and noticed some specific sequences are not being retrieved. I've used the following command: nsdpy -r 'mitochondrion[Title] AND complete[Title] OR mitochondrial[Title] AND complete[Title] ' -L Iberia.txt -t, where Iberia.txt is a list of 109 species. In this case, I noticed that at least for Scardinius erythrophthalmus no sequence is being retrieved and it should (NC_031561). However, its sequences are retrieved if the Iberia.txt file is replaced by one containing only 10 species, including Scardinius erythrophthalmus. Can you help me figure out the issue?

Thank you, 
joana

**Comment by RaphaelHebert** [comment] 2024-01-22 19:33
Hello Joana,

Thank you for your feedback on this bug.
I will have a look at it asap!
Would it be possible to have the Iberia.txt to recreate this bug?

**Comment by Joana-V** [comment] 2024-01-24 16:53
Hi, 
Here is the file :)
[IberiaFish_mt_190124.txt](https://github.com/RaphaelHebert/nsdpy/files/14041387/IberiaFish_mt_190124.txt)

Thank you

**Comment by RaphaelHebert** [comment] 2024-01-27 15:24
Hello @Joana-V,

It looks like your issue is similar to the one described in [Issue 8](https://github.com/RaphaelHebert/nsdpy/issues/8a). It has been fixed in the version 1.0.0 of nsdpy.
However, when I tried to reproduce. I ran  the following command:
`nsdpy -r 'mitochondrion[Title] AND complete[Title] OR mitochondrial[Title] AND complete[Title] ' -L Iberia.txt -t `
With the file you provided in [the previous comment](https://github.com/RaphaelHebert/nsdpy/issues/42#issuecomment-1908540612) (just renamed it to Iberia.txt).
In the fasta file 'sequences.fasta' if I run 
`grep NC_031561 sequences.fasta` 
it returns:
`>NC_031561.1 Scardinius erythrophthalmus mitochondrial DNA, complete genome`
Then manually check the sequences.fasta file I can find the whole DNA sequence for this taxa.
I your version of nsdpy the 1.0.0 ?
I will check my results more in detail and keep investigating this bug.

**Comment by Joana-V** [comment] 2024-01-29 10:59
Hi, 

The issue was indeed my version. Now that I used the 1.0.0 it's ok. 

Thank you for the help, 
joana

**Comment by RaphaelHebert** [comment] 2024-02-04 20:58
@Joana-V 
Thank you for your feedback. Feedbacks and ideas to improve this package are always welcome!

**Comment by RaphaelHebert** [comment] 2024-02-04 20:59
@Joana-V
Thank you for your feedback. Feedbacks and ideas to improve this package are always welcome!

**Closed as completed by RaphaelHebert** 2024-02-04 20:59 UTC
